// Anomaly detection engine for Scope Lock.
// Analyzes the audit trail after each tool call to detect unusual patterns
// that may indicate automated abuse, credential probing, or privilege escalation.

import { type AuditEntry, getAuditLog } from './audit';
import { evaluatePolicy, type RiskLevel } from './policy-engine';

export interface AnomalyAlert {
  type: 'RAPID_ESCALATION' | 'UNUSUAL_SCOPE' | 'HIGH_FREQUENCY' | 'SCOPE_HOPPING';
  severity: 'low' | 'medium' | 'high';
  message: string;
  timestamp: string;
  details: Record<string, unknown>;
}

// --- Thresholds ---

const ESCALATION_WINDOW_MS = 60_000; // 60 seconds
const HIGH_FREQUENCY_WINDOW_MS = 60_000; // 60 seconds
const HIGH_FREQUENCY_THRESHOLD = 10;
const SCOPE_HOPPING_WINDOW_MS = 30_000; // 30 seconds
const SCOPE_HOPPING_THRESHOLD = 3; // distinct connections
const UNUSUAL_SCOPE_BASELINE_COUNT = 5; // minimum calls before flagging novel tools

// --- Risk tier ordering (for escalation detection) ---

const RISK_RANK: Record<RiskLevel, number> = {
  GREEN: 0,
  AMBER: 1,
  RED: 2,
};

// --- Per-user alert store ---

const alertStore = new Map<string, AnomalyAlert[]>();

// Maximum alerts kept per user
const MAX_ALERTS_PER_USER = 100;

/**
 * Check the audit trail for anomalies after a new entry is logged.
 * Returns any new alerts generated by this entry.
 */
export function checkForAnomalies(userId: string, newEntry: AuditEntry): AnomalyAlert[] {
  const entries = getAuditLog(userId);
  const newAlerts: AnomalyAlert[] = [];
  const now = newEntry.timestamp;

  // --- 1. RAPID_ESCALATION ---
  // If the user went from GREEN to RED within 60 seconds
  const escalationAlert = detectRapidEscalation(entries, newEntry, now);
  if (escalationAlert) {
    newAlerts.push(escalationAlert);
  }

  // --- 2. HIGH_FREQUENCY ---
  // If more than 10 tool calls in the last 60 seconds
  const frequencyAlert = detectHighFrequency(entries, now);
  if (frequencyAlert) {
    newAlerts.push(frequencyAlert);
  }

  // --- 3. SCOPE_HOPPING ---
  // If 3+ distinct connections accessed within 30 seconds
  const hoppingAlert = detectScopeHopping(entries, now);
  if (hoppingAlert) {
    newAlerts.push(hoppingAlert);
  }

  // --- 4. UNUSUAL_SCOPE ---
  // If a tool that has never been used before is suddenly called (after baseline)
  const unusualAlert = detectUnusualScope(entries, newEntry);
  if (unusualAlert) {
    newAlerts.push(unusualAlert);
  }

  // Persist new alerts
  if (newAlerts.length > 0) {
    const existing = alertStore.get(userId) ?? [];
    existing.push(...newAlerts);
    // Cap stored alerts
    if (existing.length > MAX_ALERTS_PER_USER) {
      alertStore.set(userId, existing.slice(-MAX_ALERTS_PER_USER));
    } else {
      alertStore.set(userId, existing);
    }
  }

  return newAlerts;
}

/**
 * Return all active alerts for a user.
 */
export function getActiveAlerts(userId: string): AnomalyAlert[] {
  return alertStore.get(userId) ?? [];
}

/**
 * Clear all alerts for a user.
 */
export function clearAlerts(userId: string): void {
  alertStore.delete(userId);
}

// --- Detection functions ---

function detectRapidEscalation(
  entries: AuditEntry[],
  newEntry: AuditEntry,
  now: string,
): AnomalyAlert | null {
  const newRisk = newEntry.riskLevel as RiskLevel;
  // Only flag if the new entry is RED
  if (RISK_RANK[newRisk] < 2) return null;

  const nowMs = new Date(now).getTime();
  const windowStart = nowMs - ESCALATION_WINDOW_MS;

  // Look for a GREEN entry within the escalation window
  const recentGreen = entries.find((e) => {
    const ts = new Date(e.timestamp).getTime();
    return ts >= windowStart && (e.riskLevel as RiskLevel) === 'GREEN' && e.id !== newEntry.id;
  });

  if (recentGreen) {
    const elapsedMs = nowMs - new Date(recentGreen.timestamp).getTime();
    const elapsedSec = Math.round(elapsedMs / 1000);
    return {
      type: 'RAPID_ESCALATION',
      severity: 'high',
      message: `Rapid privilege escalation detected \u2014 went from read-only to write operations in under ${elapsedSec} seconds.`,
      timestamp: now,
      details: {
        fromTool: recentGreen.toolName,
        fromRisk: recentGreen.riskLevel,
        toTool: newEntry.toolName,
        toRisk: newEntry.riskLevel,
        elapsedMs,
      },
    };
  }

  return null;
}

function detectHighFrequency(entries: AuditEntry[], now: string): AnomalyAlert | null {
  const nowMs = new Date(now).getTime();
  const windowStart = nowMs - HIGH_FREQUENCY_WINDOW_MS;

  const recentCalls = entries.filter((e) => new Date(e.timestamp).getTime() >= windowStart);

  if (recentCalls.length > HIGH_FREQUENCY_THRESHOLD) {
    return {
      type: 'HIGH_FREQUENCY',
      severity: 'medium',
      message: `Unusual call frequency \u2014 ${recentCalls.length} tool calls in the last minute. Possible automated abuse.`,
      timestamp: now,
      details: {
        callCount: recentCalls.length,
        windowMs: HIGH_FREQUENCY_WINDOW_MS,
        threshold: HIGH_FREQUENCY_THRESHOLD,
        tools: [...new Set(recentCalls.map((e) => e.toolName))],
      },
    };
  }

  return null;
}

function detectScopeHopping(entries: AuditEntry[], now: string): AnomalyAlert | null {
  const nowMs = new Date(now).getTime();
  const windowStart = nowMs - SCOPE_HOPPING_WINDOW_MS;

  const recentEntries = entries.filter((e) => new Date(e.timestamp).getTime() >= windowStart);
  const distinctConnections = new Set(recentEntries.map((e) => e.connection));

  if (distinctConnections.size >= SCOPE_HOPPING_THRESHOLD) {
    const connections = [...distinctConnections];
    return {
      type: 'SCOPE_HOPPING',
      severity: 'medium',
      message: `Rapid service switching \u2014 accessed ${connections.join(', ')} within 30 seconds.`,
      timestamp: now,
      details: {
        connections,
        connectionCount: connections.length,
        windowMs: SCOPE_HOPPING_WINDOW_MS,
      },
    };
  }

  return null;
}

function detectUnusualScope(
  entries: AuditEntry[],
  newEntry: AuditEntry,
): AnomalyAlert | null {
  // Only apply after the user has established a baseline
  // The newEntry is already in entries (it was logged before this check),
  // so we need at least UNUSUAL_SCOPE_BASELINE_COUNT + 1 entries total
  if (entries.length < UNUSUAL_SCOPE_BASELINE_COUNT + 1) return null;

  // Check all entries BEFORE the new one for the same tool
  const priorEntries = entries.filter((e) => e.id !== newEntry.id);
  const priorTools = new Set(priorEntries.map((e) => e.toolName));

  if (!priorTools.has(newEntry.toolName)) {
    const policy = evaluatePolicy(newEntry.toolName, {});
    return {
      type: 'UNUSUAL_SCOPE',
      severity: policy.level === 'RED' ? 'high' : 'low',
      message: `First-time access to ${newEntry.toolName} detected. This tool has ${policy.level} risk level.`,
      timestamp: newEntry.timestamp,
      details: {
        toolName: newEntry.toolName,
        riskLevel: policy.level,
        priorToolCount: priorTools.size,
        totalCallCount: priorEntries.length,
      },
    };
  }

  return null;
}
